# Generated by Django 5.2.7 on 2026-04-09 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('AC', 'Air Conditioner'), ('FRIDGE', 'Refrigerator'), ('LIGHT', 'Lighting'), ('FAN', 'Fan'), ('TV', 'Television'), ('OTHER', 'Other')], max_length=20)),
                ('power_rating', models.FloatField(help_text='Power rating in Watts')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('power_usage', models.FloatField(help_text='Watts used')),
                ('energy_consumed', models.FloatField(help_text='Wh consumed')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_app.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_threshold', models.FloatField(default=10.0, help_text='kWh per day')),
                ('weekly_threshold', models.FloatField(default=70.0, help_text='kWh per week')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
